### ISSUE TITLE
Add cpio to fpm Dockerfile

### ISSUE THREAD

**Issue by adrianlzt** [Tenzer/dockerfiles#1]
When I try to convert a rpm to a deb file it returns this error:
```
root@bd4ae3540c9a:/mnt# fpm -s rpm -t deb name.x86_64.rpm
sh: 1: cpio: not found
```

I have fixed it doing in the container:
```
apt update
apt install cpio
```

**Comment by adrianlzt** [comment]
Thanks!

**Comment by Tenzer** [comment]
You're welcome. Thanks for reporting this!

**Comment by Tenzer** [comment]
There's currently a build running to update `tenzer/fpm`, should be done soon: https://hub.docker.com/r/tenzer/fpm/builds/bofaxt4dmac63hthf82v5vi/.
